### ISSUE TITLE
URL-friendly encoding recurses

### ISSUE THREAD

**Issue by PanderMusubi** [ChristopherGittner/OSMBugs#9] opened 2017-06-06 19:52 UTC
Use of double quotes results in URL-friendly encoding, but the resulting percent characters are encoded again. See screenshot. Please fix this.

![tmp_8972-screenshot_20170606-2149291619097369](https://user-images.githubusercontent.com/198964/26848870-4b65deee-4b02-11e7-8f82-e6b35249d407.png)

**Comment by PanderMusubi** [comment] 2017-06-06 19:54
Related question, how can I quickly report this bug report is false positive and related rules need improving?

**Comment by ChristopherGittner** [comment] 2017-08-12 16:00
I was trying to reproduce the Error you described. The comments i enter, with or without double quotes are correctly send to the Keepright Server. I tested this from the Website and the App.

Does the (false positive) relate to this Bug? 
What do you mean by "the rules need improving"?

**Comment by PanderMusubi** [comment] 2017-08-15 14:49
The comments get messed up when saving again and again from the app.

The false positive indeed concerns this bug. When the genus or species in Dutch (:nl) starts with a proper name, like `Hollandse` in `Hollandse iep`, then that is not an error. If you can help how a list of exceptions could be set up, I would gladly help with that.

**Comment by ChristopherGittner** [comment] 2017-08-21 15:47
Ok i found the note you mentioned and opened the Bug, and saved it again this time with double quotes.
For me everything is working as intended. Can you please confirm that this is still happening in the current version? Maybe with another Bug?

See the Screenshot
![screenshot_20170816-190524](https://user-images.githubusercontent.com/4542892/29527084-f6cee66a-8697-11e7-9896-4d4a76af563d.jpg)


The second thing is, that this report is probalby correct. If you open Tagwatch for this tag, you will see only a couple of Entries for "Hollandse iep". Over 500 entries have the tag in lowercase letters, as the report suggests "hollandse iep". See [https://taginfo.openstreetmap.org/keys/species%3Anl#values]
This App does not generate the Bugs. The bug is generated by Keepright. If you think, that this is still an error, you need should contact the Administrator at keepright.at

**Comment by eehpcm** [comment] 2017-09-16 22:36
Whatever the language (it doesn't just apply to Dutch), the genus **should** be capitalized but the species should not.

So PanderMusubi was wrong to imply the species should be capitalized.  But his examples did not capitalize the species, so I think that was a mistake in how he described the problem.

Tagwatch may indeed have over 500 usages of "hollandse iep," but that just means that over 500 people are ignorant of proper usage or too lazy to use the shift key. :)

Actually, the way the tag is described and used in the wiki is messed up.  There is a species tag and a genus tag, but the genus tag is supposed to be only used if there is no species tag, and the species tag is misused to mean the binomial name (_Genus_ _species_).

All that said, the wiki examples of binomial names in the species [sic] tag capitalize the genus.

**Comment by PanderMusubi** [comment] 2017-09-18 11:10
Source of many of the inconsistencies is that people are indeed too lazy to use the shift key or they do not know that there is a requirement to use proper capitalization. What also happens is that people use the same value (genus or species) for both fields.

After some more reading, indeed it is as you say. there is in Dutch also official spelling, but that is not capitalized and hence differs from the scientific name. Also in the German examples is a slight inconsistency, see `English Oak` and `French oak` in https://wiki.openstreetmap.org/wiki/DE:Key:species

To get practical, I would like help clean up `species:nl` https://taginfo.openstreetmap.org/keys/species%3Anl#valuesa and `genus:nl` https://taginfo.openstreetmap.org/keys/genus:nl#values how would I go about doing that? Subsequently, use a similar approach for `species` and `genus`.

**Comment by eehpcm** [comment] 2017-09-18 12:50
I'm a relative n00b to OSM, so my advice on this is probably not the best you can get.

I can see lots of problems in trying to fix this.

I don't know about Dutch, but in English the term "species" is ambiguous.  We happily say that cats are species and dogs are species.  But in biology a species (same as previous usage) is identified by a genus and a **species name.**  Biologists make the distinction between a species (type of animal, such as cat) and its binomial nomenclature (_Felis cattus_), of which _cattus_ is the species name.  The combination of genus and species name is unique.  Many species may be in the same genus.  The big problem is that very different species in different genera may share the same species name: _Berberis darwinii_, _Nothura darwinii_,  _Gephyroberyx darwinii_, _Cyttaria darwinii_, etc.

So on OSM species= is usually used for binomial name.  Genus= is used to give a more vague definition without narrowing it down to a single species.  I doubt any mapper has used both genus= and species= together to give a binomial name, and giving species name without genus would lead to much confusion (species=darwinii without a genus, for example).  Oh, and don't forget that "binomial" names these days sometimes include sub-species such as _Homo sapiens neanderthalis_ (arguably we should be in _Pan_ with the other great apes).  It would be hard to come up with something better and make it stick when used by typical mappers, such as adding binomial= and getting people to use it.  You'd have to go through a discussion process on the forums, escalate it to a proposal, and probably get voted down because it's impractical.  They'd just say to use species= for the binomial name _or_ the common name and genus= when you want to be more vague.

Changing the capitalization, you can do.  You can't change the taginfo database directly, because it reflects what values are actually used.  It describes what is, not what ought to be.  So the only way you could change taginfo is find each occurrence on the map and change it _on the map_.  One value at a time.  Tedious, but eventually taginfo would show more capitalized genera than uncapitalized ones.  Except you probably don't have the patience.

You could write a bot that goes around fixing things up on the map, but that is **strongly discouraged** unless you **really** know what you're doing.  Since you had to ask, you don't. :)

About the best you could realistically do is change any bad examples in the wiki and add text strongly encouraging correct capitalization.  And maybe change bad usage as you encounter it, rather than hunting down all bad usage globally.

And with that said, I'm not sure that the tags genus:nl and species:nl (or any other language ought to be used for binomial names (which are always in Latin) but should be used for common names.  In which case different rules apply.  German and French have strict rules about such matters, English is a lot more _laissez faire_ (we actually do have rules about punctuation and capitalization but they're set by individual publishing houses in manuals of style).  But if you do use species:nl for a common name then genus:nl shouldn't be used at all.  Because it's like "cat" in English versus _Felis cattus_.  The common name of a species doesn't have a genus, although it may consist of more than one word (duck-billed platypus).

All of which has taken us way off topic.  I suggest you move things to the openstreetmap forums if you need to discuss it further.  More because I'm a relative n00b than to keep it out of here.

**Comment by ChristopherGittner** [comment] 2017-09-28 13:50
This went a little Off-Topic :-)

I will close this issue. If this Bug still persists please comment!

**Closed by ChristopherGittner** 2017-09-28 13:50 UTC
